old_sound_rabbit_mq:
    connections:
        default:
            host:     127.0.0.1
            port:     5672
            user:     guest
            password: guest
            vhost:    '/'
            lazy:     false
#            connection_timeout: 3
#            read_write_timeout: 3
#
#            # requires php-amqplib v2.4.1+ and PHP5.4+
#            keepalive: false
#
#            # requires php-amqplib v2.4.1+
#            heartbeat: 0
    producers:
        mushroom_queue:
            connection:       default
            queue_options: { name: 'mushroom', durable: true }
            exchange_options: { name: 'mushroom', type: direct }
        shop_queue:
            connection:       default
            queue_options: { name: 'shop', durable: true }
            exchange_options: { name: 'shop', type: direct }
        wine_queue:
            connection:       default
            queue_options: { name: 'wine', durable: true }
            exchange_options: { name: 'wine', type: direct }
    consumers:
        save_mushroom:
            connection:       default
            exchange_options: { name: 'mushroom', type: direct }
            queue_options:    { name: 'mushroom' }
            callback:         save_mushroom
        save_shop:
            connection:       default
            exchange_options: { name: 'shop', type: direct }
            queue_options:    { name: 'shop' }
            callback:         save_shop
        save_wine:
            connection:       default
            exchange_options: { name: 'wine', type: direct }
            queue_options:    { name: 'wine' }
            callback:         save_wine
