old_sound_rabbit_mq:
    connections:
        default:
            host:     '127.0.0.1'
            port:     5672
            user:     'admin'
            password: 'pass'
            vhost:    '/'
            lazy:     false
#            connection_timeout: 3
#            read_write_timeout: 3
#
#            # requires php-amqplib v2.4.1+ and PHP5.4+
#            keepalive: false
#
#            # requires php-amqplib v2.4.1+
#            heartbeat: 0
    producers:
        mushroom_queue:
            connection:       default
            queue_options: { name: 'mushroom', durable: true }
            exchange_options: { name: 'mushroom', type: direct }
    consumers:
        save_mushroom:
            connection:       default
            exchange_options: { name: 'mushroom', type: direct }
            queue_options:    { name: 'mushroom' }
            callback:         save_mushroom