mushroom.view:
    path:     /
    defaults: { _controller: MainBundle:Default:mushroom }
shop.view:
    path:     /shop
    defaults: { _controller: MainBundle:Default:shop }
producer.send.mushrooms:
    path:     /mushrooms
    defaults: { _controller: MainBundle:Mushroom:send }
    methods:  [PUT]

producer.send.shops:
    path:     /shops
    defaults: { _controller: MainBundle:Shop:send }
    methods:  [PUT]