services:
    mushroom_queue:
        class: MainBundle\Service\MushroomQueueService
        arguments:
            - @old_sound_rabbit_mq.mushroom_queue_producer
    save_mushroom:
        class: MainBundle\Service\MushroomSaveService
        arguments:
            - @doctrine.orm.entity_manager

    shop_queue:
        class: MainBundle\Service\ShopQueueService
        arguments:
            - @old_sound_rabbit_mq.shop_queue_producer
    save_shop:
        class: MainBundle\Service\ShopSaveService
        arguments:
            - @doctrine.orm.entity_manager