services:
    mushroom_queue:
        class: MainBundle\Service\MushroomQueueService
        arguments:
            - @old_sound_rabbit_mq.mushroom_queue_producer
    save_mushroom:
        class: MainBundle\Service\MushroomSaveService
        arguments:
            - @doctrine.orm.entity_manager
            - @service_container